/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package motorpartshopsoftware;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import javax.swing.JOptionPane;
import static motorpartshopsoftware.AddDetails.userClass;
/**
 *
 * @author RITESH
 */
public class Billing extends javax.swing.JFrame {

    /**
     * Creates new form Billing
     */
    Connection connect = DriverManager.getConnection("jdbc:derby://localhost:1527/MotorPartShopDB","riteshzd","gocoronago");
   
    static String userClass;
    int stockQuantity;
    public Billing(String str) throws SQLException {
        userClass = str;
        stockQuantity = 0;
        initComponents();
        
        LocalDate localDate = LocalDate.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/LLLL/yyyy");
        String dateString = localDate.format(formatter);
        dateText.setText(dateString);
        
        PreparedStatement stmnt = connect.prepareStatement("select count(*) from BILLINGINFO");
        ResultSet rs = stmnt.executeQuery();
        int count = 0;
        while(rs.next())
            count = rs.getInt(1);
        billIDText.setText(Integer.toString(count+1));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        amountText = new javax.swing.JTextField();
        quantityText = new javax.swing.JTextField();
        partIDText = new javax.swing.JTextField();
        customerNameText = new javax.swing.JTextField();
        billIDText = new javax.swing.JTextField();
        dateText = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        getAmountButton = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("BILLING");

        jLabel2.setText("Bill ID");

        jLabel3.setText("Customer Name");

        jLabel4.setText("Part ID");

        jLabel5.setText("Quantity");

        jLabel6.setText("Amount");

        jLabel7.setText("Date");

        amountText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        amountText.setText("0");
        amountText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountTextActionPerformed(evt);
            }
        });

        quantityText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        quantityText.setText("0");
        quantityText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityTextActionPerformed(evt);
            }
        });

        dateText.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        getAmountButton.setText("Get Amount");
        getAmountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getAmountButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(quantityText, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(partIDText)
                    .addComponent(customerNameText)
                    .addComponent(billIDText)
                    .addComponent(dateText)
                    .addComponent(amountText))
                .addGap(18, 18, 18)
                .addComponent(getAmountButton)
                .addContainerGap(98, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(180, 180, 180))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(submitButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(backButton)
                        .addGap(7, 7, 7))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(billIDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(customerNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(partIDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(quantityText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(amountText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(getAmountButton))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitButton)
                    .addComponent(backButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void amountTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountTextActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_amountTextActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        welcomePage obj = new welcomePage(userClass);
        obj.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void quantityTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityTextActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_quantityTextActionPerformed

    private void getAmountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getAmountButtonActionPerformed
        // TODO add your handling code here:
        if(partIDText.getText().equals(""))
            JOptionPane.showMessageDialog(null, "Invalid ID entered..!!");
        else {
            PreparedStatement stmnt;
            try {
                stmnt = connect.prepareStatement("select * from MOTORPARTDETAILS where ID=?");
                stmnt.setInt(1,Integer.parseInt(partIDText.getText()));

                ResultSet rs = stmnt.executeQuery();
                int price=0;
                while(rs.next()){
                    price = rs.getInt(3);
                    stockQuantity = rs.getInt(4);
                }
                int quantity = Integer.parseInt(quantityText.getText());
                amountText.setText(Integer.toString(price*quantity));
            } catch (SQLException ex) {
                Logger.getLogger(Billing.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_getAmountButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
       
        if(customerNameText.getText().equals("")||partIDText.getText().equals("")||quantityText.getText().equals("0"))
           JOptionPane.showMessageDialog(null, "Invalid data entered..!!");
        else{
            try {
                // TODO add your handling code here:

                PreparedStatement stmnt = connect.prepareStatement("insert into BILLINGINFO(BillID,Date,CustomerName,PartID,Quantity,Amount)values(?,?,?,?,?,?)");
                stmnt.setInt(1,Integer.parseInt(billIDText.getText()));
                LocalDate localDate = LocalDate.now();
                stmnt.setDate(2, java.sql.Date.valueOf(localDate)); //convert localDate type to Date type
                stmnt.setString(3, customerNameText.getText());
                stmnt.setInt(4,Integer.parseInt(partIDText.getText()));
                stmnt.setInt(5, Integer.parseInt(quantityText.getText()));
                stmnt.setInt(6,Integer.parseInt(amountText.getText()));

                int check = stmnt.executeUpdate();
                if(check>0)
                    System.out.println("Bill with ID "+billIDText+" has been processed successfully..!!");
            } catch (SQLException ex) {
                Logger.getLogger(Billing.class.getName()).log(Level.SEVERE, null, ex);
            }

            try {
                PreparedStatement updateStmnt = connect.prepareStatement("update MOTORPARTDETAILS set Quantity=? where ID=?");
                System.out.println(stockQuantity);
                System.out.println(quantityText.getText());
                updateStmnt.setInt(1,stockQuantity-Integer.parseInt(quantityText.getText()));
                updateStmnt.setInt(2,Integer.parseInt(partIDText.getText()));
                String quantityVal = Integer.toString(stockQuantity-Integer.parseInt(quantityText.getText()));
                int check = updateStmnt.executeUpdate();
                if(check>0)
                    System.out.println("Stock of MotorPart having ID "+partIDText+" is "+quantityVal+" now..!!");
            } catch (SQLException ex) {
                Logger.getLogger(Billing.class.getName()).log(Level.SEVERE, null, ex);
            }

            String weekDays[]={"Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"};
            Calendar clndr = Calendar.getInstance();
            int dayNum = clndr.get(Calendar.DAY_OF_WEEK)-1;
            String presentDay = weekDays[dayNum];
            PreparedStatement updateDailySalesStmnt;
            try {
                String getQuery = "select "+presentDay+" from WEEKLYSTOCKSOLD where partID=?";
                PreparedStatement getPrevQuantityStmnt  = connect.prepareStatement(getQuery);
                getPrevQuantityStmnt.setInt(1, Integer.parseInt(partIDText.getText()));
                ResultSet rs = getPrevQuantityStmnt.executeQuery();
                int salesTillNow = 0;
                while(rs.next())
                    salesTillNow=rs.getInt(1);


                String queryStatement = "update WEEKLYSTOCKSOLD set "+presentDay+"=? where partID=?";
                updateDailySalesStmnt = connect.prepareStatement(queryStatement);
                updateDailySalesStmnt.setInt(1, salesTillNow+Integer.parseInt(quantityText.getText()));
                updateDailySalesStmnt.setInt(2,Integer.parseInt(partIDText.getText()));
                int updateCheck = updateDailySalesStmnt.executeUpdate();
                if(updateCheck>0)
                    System.out.println("Daily Sales is updated on the WEEKLYSTOCKSOLD db..!!");
            } catch (SQLException ex) {
                Logger.getLogger(Billing.class.getName()).log(Level.SEVERE, null, ex);
            }


            setVisible(false);
            welcomePage obj = new welcomePage(userClass);
            obj.setVisible(true);
            }
    }//GEN-LAST:event_submitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Billing(userClass).setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Billing.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountText;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField billIDText;
    private javax.swing.JTextField customerNameText;
    private javax.swing.JTextField dateText;
    private javax.swing.JButton getAmountButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField partIDText;
    private javax.swing.JTextField quantityText;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
