/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package motorpartshopsoftware;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import motorpartshopsoftware.LoginPage;
import motorpartshopsoftware.AddDetails;
/**
 *
 * @author RITESH
 */
public class welcomePage extends javax.swing.JFrame {

    /**
     * Creates new form welcomePage
     */
    static String userClass;
    public welcomePage(String str) {
        userClass = str;
        System.out.println(userClass+" has logged in..!!");
        initComponents();
        user.setText("You have logged in as "+userClass);
        if(userClass.equals("Owner")){
            billing.setVisible(false);
            addStock.setVisible(false);
            updateStock.setVisible(false);
        } else if(userClass.equals("Keeper")){
            statistics.setVisible(false);
            requiredStock.setVisible(false);
            updateStock.setVisible(false);
        } else { //for Sales Exec
            billing.setVisible(false);
            statistics.setVisible(false);
        }
    }

    welcomePage() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        user = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        billing = new javax.swing.JButton();
        currentStock = new javax.swing.JButton();
        requiredStock = new javax.swing.JButton();
        addStock = new javax.swing.JButton();
        statistics = new javax.swing.JButton();
        updateStock = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        user.setText("You have logged in as ...");

        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        billing.setText("Billing");
        billing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billingActionPerformed(evt);
            }
        });

        currentStock.setText("Current Stock");
        currentStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentStockActionPerformed(evt);
            }
        });

        requiredStock.setText("Required Stock");
        requiredStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requiredStockActionPerformed(evt);
            }
        });

        addStock.setText("Add Stock");
        addStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStockActionPerformed(evt);
            }
        });

        statistics.setText("Sales Statistics");
        statistics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statisticsActionPerformed(evt);
            }
        });

        updateStock.setText("Update Stock");
        updateStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateStockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(157, Short.MAX_VALUE)
                .addComponent(user)
                .addGap(123, 123, 123))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(logoutButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(addStock)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(billing))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(updateStock)
                            .addComponent(requiredStock)
                            .addComponent(currentStock)
                            .addComponent(statistics))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(user)
                        .addGap(39, 39, 39)
                        .addComponent(billing))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(addStock)
                        .addGap(18, 18, 18)
                        .addComponent(updateStock)))
                .addGap(18, 18, 18)
                .addComponent(currentStock)
                .addGap(18, 18, 18)
                .addComponent(statistics)
                .addGap(18, 18, 18)
                .addComponent(requiredStock)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(logoutButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        LoginPage obj;
        try {
            obj = new LoginPage();
            obj.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(welcomePage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void addStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStockActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        AddDetails obj = new AddDetails(userClass);
        obj.setVisible(true);
    }//GEN-LAST:event_addStockActionPerformed

    private void updateStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateStockActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        UpdateStock obj =new UpdateStock(userClass);
        obj.setVisible(true);
    }//GEN-LAST:event_updateStockActionPerformed

    private void currentStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentStockActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        try {
            CheckStock obj = new CheckStock(userClass);
            obj.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(welcomePage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_currentStockActionPerformed

    private void billingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billingActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Billing obj;
        try {
            obj = new Billing(userClass);
            obj.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(welcomePage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_billingActionPerformed

    private void statisticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statisticsActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        SalesStatistics obj;
        try {
            obj = new SalesStatistics(userClass);
            obj.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(welcomePage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_statisticsActionPerformed

    private void requiredStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requiredStockActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        RequiredStock obj;
        try {
            obj = new RequiredStock(userClass);
            obj.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(welcomePage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_requiredStockActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(welcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(welcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(welcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(welcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new welcomePage(userClass).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addStock;
    private javax.swing.JButton billing;
    private javax.swing.JButton currentStock;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton requiredStock;
    private javax.swing.JButton statistics;
    private javax.swing.JButton updateStock;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
